### ISSUE TITLE
Name bikeshedding

### ISSUE THREAD

**Issue by lucacasonato** [tc39-transfer/proposal-import-reflection#9]
The current name of the proposal is not very descriptive of what it does: evaluator attributes do not change how a module is evaluated. It instead changes how a module is reflected (represented). Would _reflector attributes_ be a better name? Or representation attributes?

Ref #6

**Comment by guybedford** [comment]
I've created a PR in https://github.com/tc39-transfer/proposal-evaluator-attributes/pull/15 to rename the proposal to import reflection. Any eyes on review appreciated.

**Comment by guybedford** [comment]
The proposal has now been renamed to the import reflection proposal.
